runtime: python39
instance_class: F2

entrypoint: gunicorn -b :$PORT --workers 3 --threads 2 landing.wsgi:application

automatic_scaling:
  max_instances: 20
  min_instances: 1
  target_cpu_utilization: 0.65

env_variables:
  DJANGO_SETTINGS_MODULE: "landing.settings"
  SECRET_KEY: "django-insecure-ay!=7)av-h63%y7o#aif8$9mzwm8vh3i-xkz+6#(040d6a%r!q"
  DJANGO_DEBUG: True
  GOOGLE_APPLICATION_CREDENTIALS: "orest-birthday-777-61eb64162f83.json"
  GS_BUCKET_NAME: "orest-birthday-static"

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto